name: Task
description: Create a new task or to-do item.
title: "[TASK] - "
body:
  - type: markdown
    attributes:
      value: |
        Thank you for creating a task! Please provide the following details to help us track and manage the task effectively.
  - type: input
    id: branch_name
    attributes:
      label: Branch Name
      description: Suggested branch name for implementing this task
      placeholder: task/[issue-id]
      value: task/
  - type: textarea
    id: task_description
    attributes:
      label: Task Description
      description: What needs to be done?
      placeholder: Provide a clear and concise description of the task.
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: What conditions must be met for this task to be considered complete?
      placeholder: List the specific criteria that must be satisfied to mark this task as complete.
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Are there any other tasks or issues that this task depends on?
      placeholder: List any dependencies or prerequisites for this task.
